export enum UserFields {
  ID = 'id',
  PASSWORD = 'password',
  EMAIL = 'email',
  EMAIL_VERIFIED = 'email_verified',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  ROLES = 'roles',
  STATUS = 'status',
  DATE_CREATED = 'date_created',
  LAST_ACCESS = 'last_access',
  COACHES = 'coaches',
  MUNICIPALITY = 'municipality',
  INSTITUTION = 'institution',
}
